import React from "react";
import Resource, {ResourceState} from "./Resource";

interface IProps {}
interface IState extends ResourceState {}
export default class StorageBucket extends Resource<IProps, IState> {
	static defaultProps = {
		...Resource.defaultProps,

		//Type of resource for labels
		resource: "Storage Bucket",

		//For autogenerated random IDs
		randomPrefix: "Storage-Bucket-",

		//Length of random hash
		randomGroups: 5,

		//The "type" to send to the backend
		resourceType: "googleStorageBucket"
	};

	render() {
		return super.render();
	}
}
