#!/bin/sh


echo "running"

path=$( echo "$0" | sed -E 's/^(backend|frontend)\///g' )
. "$(dirname "$path")/_/husky.sh"

FRONTEND=0
BACKEND=0
STATUS=0

git diff --cached --name-only | grep '^frontend' >/dev/null && FRONTEND=1
git diff --cached --name-only | grep '^backend' >/dev/null && BACKEND=1

FILES=$( git status -s | grep '^[^ ?]' | cut -c 4- | xargs )

[ $FRONTEND -eq 1 ] && {
	cd frontend
	npm run format && npm run lint:fix || STATUS=1
	cd ..
}
[ $BACKEND -eq 1 ] && {
	cd backend
	npm run format && npm run lint:fix || STATUS=1
	cd ..
}

echo "$FILES" | xargs -n1 -I {} [ -f "{}" ] && git add
exit $STATUS
