name: Build and Deploy Backend to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: '${{ secrets.SERVICE }}'
        image: 'gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}'
        region: 'us-west1'
        env_vars: 'CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}'
