name: Build and Deploy Frontend to Github Pages

on:
  push:
    branches:
      - main
      - cicd
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: cd frontend && npm install

    - name: Build frontend
      run: cd frontend && npm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: frontend/dist # The folder the action should deploy.
        ssh-key: ${{ secrets.DEPLOY_KEY }}
