name: Terraform

on:
  push:
    branches:
      - terraform

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v1

    - id: 'checkout'
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Setup terraform'
      run: 'terraform init'

    - name: 'Initialize terraform env vars'
      run: './createTerraformVarsFile.sh CONNECTION_STRING GITHUB_CLIENT_ID GITHUB_CLIENT_SECRET'

    - name: 'Terraform plan'
      run: 'TF_LOG=ERROR terraform apply -lock=false'
